version: "2"
services:
  mongo:
    image: mongo
    ports:
      - '27018:27017'
  rabbitmq:
    image: rabbitmq
  bridge:
    build:
      context: ..
      dockerfile: ./dockerfiles/bridge-develop.dockerfile
    ports:
      - '6383:6382'
    working_dir: '/bridge'
    command: /usr/bin/env npm run start-test
    environment:
      NODE_ENV: 'test'
    volumes:
      - ../bin:/bridge/bin
      - ../lib:/bridge/lib
    links:
      - mongo
      - rabbitmq
