version: "2"
services:
  mongo:
    image: mongo
    ports:
      - '27017:27018'
  rabbitmq:
    image: rabbitmq
  bridge:
    build:
      context: ..
      dockerfile: ./dockerfiles/bridge-develop.dockerfile
    ports:
      - '6382:6383'
    working_dir: '/bridge'
    command: /usr/bin/env node /bridge/bin/storj-bridge.js
    environment:
      NODE_ENV: 'develop'
    volumes:
      - ../bin:/bridge/bin
      - ../lib:/bridge/lib
    links:
      - mongo
      - rabbitmq
  ruby:
    build:
      context: ..
      dockerfile: ./dockerfiles/selenium-test.dockerfile
    working_dir: '/bridge'
    command: ['/usr/bin/env', 'cucumber']
    volumes:
      - ../features:/bridge/features
      - ../script:/bridge/script
    links:
      - bridge
      - mongo
