version: "2"
services:
  ruby:
    build:
      context: ..
      dockerfile: ./dockerfiles/selenium-test.dockerfile
    working_dir: '/bridge'
    command: ['/usr/bin/env', 'cucumber']
    volumes:
      - ../features:/bridge/features
      - ../script:/bridge/script
